# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: psql-pv-flask
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   local:
#     path: /storage/db/flask
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: kubernetes.io/hostname
#               operator: In
#               values:
#                 - minikube

apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-pv-flask
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /storage/db/flask
    type: DirectoryOrCreate
