apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-deployment
  namespace: dev
  labels:
    app: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: panchanandevops/python-flask-app:2.0.8
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
  namespace: dev
  labels:
    app: flask-api
spec:
  selector:
    app: flask-api
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
