apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: dev
  labels:
    app: flask-api
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres-statefulset-0.postgres-service.dev.svc.cluster.local:5432/postgres
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
