apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pvc-flask
  namespace: dev
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
